server:
  port: 8080

spring:
  application:
    name: temporal-demo
  datasource:
    url: jdbc:h2:mem:bisbis10;DB_CLOSE_DELAY=-1
    username: bisbis10
    password: bisbis10
    driverClassName: org.h2.Driver
    platform: h2
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true